### ISSUE TITLE
rsvg.dll problem

### ISSUE THREAD

**Issue by NahuelGrasso** [jeroenooms/rsvg#3]
Hello, I am trying to install this package using **install_github("jeroenooms/rsvg")** . 
I throws the following lines:
Downloading github repo jeroenooms/rsvg@master
Installing rsvg
"C:/PROGRA~1/RRO/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/user/AppData/Local/Temp/RtmpiilkpK/devtools6843af423d5/jeroenooms-rsvg-0e85605"  \
  --library="C:/Program Files/RRO/R-3.2.2/library" --install-tests 

Multithreaded BLAS/LAPACK libraries detected. Using 2 cores for math algorithms.
- installing _source_ package 'rsvg' ...
  *\* libs
  rm -f _.so *.o *.dll
  "C:/PROGRA~1/RRO/R-32~1.2/bin/x64/Rscript.exe" "../tools/winlibs.R"
  Multithreaded BLAS/LAPACK libraries detected. Using 2 cores for math algorithms.
  Warning message:
  In download.file("https://github.com/rwinlib/rsvg/archive/v2.40.12.zip",  :
  downloaded length 14733275 != reported length 200
  cp -f ../windows/rsvg-2.40.12/bin/x64/_.dll .
  gcc -m64 -I"C:/PROGRA~1/RRO/R-32~1.2/include" -DNDEBUG -I../windows/rsvg-2.40.12/include/librsvg-2.0 -I../windows/rsvg-2.40.12/include/glib-2.0 -I../windows/rsvg-2.40.12/lib/x64/glib-2.0/include -I../windows/rsvg-2.40.12/include/gdk-pixbuf-2.0 -I../windows/rsvg-2.40.12/include/cairo    -I"c:/applications/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c init.c -o init.o
  gcc -m64 -I"C:/PROGRA~1/RRO/R-32~1.2/include" -DNDEBUG -I../windows/rsvg-2.40.12/include/librsvg-2.0 -I../windows/rsvg-2.40.12/include/glib-2.0 -I../windows/rsvg-2.40.12/lib/x64/glib-2.0/include -I../windows/rsvg-2.40.12/include/gdk-pixbuf-2.0 -I../windows/rsvg-2.40.12/include/cairo    -I"c:/applications/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c rsvg.c -o rsvg.o
  gcc -m64 -shared -s -static-libgcc -o rsvg.dll tmp.def init.o rsvg.o -L../windows/rsvg-2.40.12/lib/x64 -lrsvg-2 -lxml2 -lz -lpangocairo-1.0 -lpango-1.0 -lpangoft2-1.0 -lpangowin32-1.0 -lcairo-gobject -lcairo -lfontconfig -lfreetype -lpng16 -lpixman-1 -lexpat -lharfbuzz -lbz2 -lgdi32 -lz -lcroco-0.6 -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -lpng16 -lintl -liconv -lusp10 -ldnsapi -liphlpapi -lgdiplus -lgdi32 -lole32 -lws2_32 -Lc:/applications/extsoft/lib/x64 -Lc:/applications/extsoft/lib -LC:/PROGRA~1/RRO/R-32~1.2/bin/x64 -lR
  installing to C:/Program Files/RRO/R-3.2.2/library/rsvg/libs/x64
  *\* R
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* testing if installed package can be loaded
  Multithreaded BLAS/LAPACK libraries detected. Using 2 cores for math algorithms.
- DONE (rsvg)

After that, I try to run this code:
**library(rsvg)**
And produces the following error:
**Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Program Files/RRO/R-3.2.2/library/rsvg/libs/x64/rsvg.dll':
  LoadLibrary failure:  No se encontró el proceso especificado.(in english: specified process couldn't be found)
Error: package or namespace load failed for ‘rsvg’**

What should the problem be? and what should I do? do you have any clue? Any help appreciated.
Nahuel

**Comment by jeroenooms** [comment]
Can you just try: `install.packages("rsvg")`

**Comment by NahuelGrasso** [comment]
Thanks! I just thought that the latests version wasn't uploaded to cran.
